### ISSUE TITLE
core.async badge on index.html links to 404

### ISSUE THREAD

**Issue by jorisbontje** [onyx-platform/onyx-platform.github.io#10]
The `core.async` badge on the homepage (in index.html ) links to https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/core-async-plugin.md but this document is not available. Instead it should be linking to the AsciiDoc at https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/core-async-plugin.adoc

**Comment by lbradstreet** [comment]
Thanks. Fixed.
