### ISSUE TITLE
Include descriptive titles for Onyx website

### ISSUE THREAD

**Issue by danielcompton** [onyx-platform/onyx-platform.github.io#11]
At the moment, all the Onyx website pages seem to just have "Onyx" as their title? It could be good to change it to "Docs - Onyx" or similar?

<img width="847" alt="screenshot of safari technology preview 27-03-17 10-24-33 am" src="https://cloud.githubusercontent.com/assets/811954/24335349/a5a67782-12d7-11e7-96a2-f570133991f7.png">

**Comment by MichaelDrogalis** [comment]
@danielcompton Good tip - I'll take care of that now.

**Comment by MichaelDrogalis** [comment]
Fixed, thanks for pointing this out! Should be redeploying any minute now.
