### ISSUE TITLE
Links broken for flow condition filtering section

### ISSUE THREAD

**Issue by enragedginger** [onyx-platform/onyx-platform.github.io#7]
This chunk of the documentation isn't displaying properly

```
<div class="sect2">
<h3 id="_how_can_i_filter_segments_from_being_output_from_my_tasks"><a class="anchor" href="#_how_can_i_filter_segments_from_being_output_from_my_tasks"></a>How can I filter segments from being output from my tasks?</h3>
<div class="paragraph">
<p>Use [Flow Conditions](\{\{ "/flow-conditions.html" | prepend: page.dir |
prepend: site.baseurl }}) or return an empty vector from your
<code>:onyx/fn</code>.</p>
</div>
```

http://www.onyxplatform.org/docs/user-guide/0.9.x/#_how_can_i_filter_segments_from_being_output_from_my_tasks

<img width="941" alt="screen shot 2016-11-21 at 12 28 27 pm" src="https://cloud.githubusercontent.com/assets/2838551/20495294/15f52c9a-afe6-11e6-9067-a276db72d72c.png">

**Comment by MichaelDrogalis** [comment]
Fixed in Onyx core d536ca4f373a047206fd14a0dc5458a500d1fd6b. Thanks!
